[project]
name = "defi-groundbreaking-contract"
authors = ["Web3 Development Team"]
description = "A decentralized real estate rental platform enabling secure, transparent property transactions"
telemetry = false
requirements = []

[contracts.block-estate-marketplace]
path = "contracts/block-estate-marketplace.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
